### ISSUE TITLE
Required dependecies for Debian and derivates

### ISSUE THREAD

**Issue by tiago4171** [Sup3r-Us3r/HashCode#1]
I have installed the dependencies, are they:
python3.5, python3, python3.4 and tk
All were already installed on Debian 9 GNOME, but when running the hashcodegui he asks to install python3-tk, look:
```
tiago@Debian:~/git/HashCode$ ./hashcodegui.py 
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 36, in <module>
    import _tkinter
ImportError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./hashcodegui.py", line 11, in <module>
    from tkinter import *
  File "/usr/lib/python3.5/tkinter/__init__.py", line 38, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package

```
The last line, asks to install the package that I said.
So, this is not a issue but yeah a important note. Update the README.md
Thanks and sorry for my english

**Comment by Sup3r-Us3r** [comment]
$ sudo apt-get install python3-tk

-> Run with python3 or other version >= 3

$ python3 hashcode-en.py
^ example.
